# Mysql Database
mysql:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.99.100:
  username: mysql
  password: 123456
  
# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update